### PR TITLE
Added top entity lookup files

### PR DESCRIPTION
**Pull request by psykokwak4**

### CODE REVIEW

**Comment by ghost** [comment]
Can you please rebase this off origin/ydk_core? Thanks!

**Comment by manradhaCisco** [comment]
A couple of changes need to be made here. 
1. One the core header files are referenced using relative directory semantics .../src/entity.hpp for example this needs to be changed to "ydk/entity.hpp"
2. The namespace for the generated code should not be ydk use the bundle name if there are no name clashes (a better approach might be to use the module name as the nested namespace
3. sdk/cpp/ydk/tests/netconf/test_netconf_provider.cpp uses generated code ../../models/openconfig_bgp.h if this is deliberate move openconfig_bgp.h  and also the generated file to the test directory under ydk make sure cmake compiles those files as part of the test case.

**Comment by psykokwak4** [comment]
Change to replace relative directory semantics to "ydk/src/entity.hpp" depends on changes on CMake file, could it be changed after commits for CMake files?

**Comment by manradhaCisco** [comment]
yes that will be fine

**Pull request closed without merging**
